name: Scrape Mathnasium Data

on:
  schedule:
    # Run daily at 8 AM UTC (adjust timezone as needed)
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@master
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scraper
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        MATHNASIUM_USERNAME: ${{ secrets.MATHNASIUM_USERNAME }}
        MATHNASIUM_PASSWORD: ${{ secrets.MATHNASIUM_PASSWORD }}
      run: python scrape.py
    
    - name: Upload logs (optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: scraping-logs
        path: |
          *.log
          *.txt
